// App.tsx
import React, { useEffect, useState, useRef } from 'react';
import { OrgChart, OrgChartRef } from './components/OrgChart';
import { InputPanel } from './components/InputPanel';
import { INITIAL_DATA } from './constants';
import { OrgNode, LayoutDirection } from './types';
import { Menu, X, Ratio, Download } from 'lucide-react';
import { ChartThemeProvider, CHART_THEMES, ChartThemeId, SiteThemeId, SITE_THEMES, SiteThemeProvider, useChartTheme, useSiteTheme } from './theme';

const AppInner: React.FC = () => {
  const { siteThemeId, setSiteThemeId } = useSiteTheme();
  const { chartThemeId, setChartThemeId } = useChartTheme();
  const [data, setData] = useState<OrgNode>(INITIAL_DATA);
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [targetAspectRatio, setTargetAspectRatio] = useState<number>(1); // Default 1:1
  const chartRef = useRef<OrgChartRef>(null);

  const DEFAULT_SIDEBAR_WIDTH = (typeof window !== 'undefined' && window.innerWidth >= 1024) ? 384 : 320; // ~w-96 or w-80
  const MIN_SIDEBAR_WIDTH = 280;
  const MAX_SIDEBAR_WIDTH = 1200;
  const MIN_CHART_WIDTH = 320;
  const [sidebarWidth, setSidebarWidth] = useState<number>(DEFAULT_SIDEBAR_WIDTH);
  const isResizingRef = useRef(false);
  const suppressSidebarToggleClickRef = useRef(false);
  const resizeStartXRef = useRef(0);
  const resizeStartWidthRef = useRef(0);
  const onResizeMoveRef = useRef<((e: PointerEvent) => void) | null>(null);
  const onResizeEndRef = useRef<((e: PointerEvent) => void) | null>(null);

  const clampSidebarWidth = (width: number) => {
    const viewportMax = typeof window !== 'undefined'
      ? Math.max(MIN_SIDEBAR_WIDTH, window.innerWidth - MIN_CHART_WIDTH)
      : MAX_SIDEBAR_WIDTH;
    return Math.max(MIN_SIDEBAR_WIDTH, Math.min(width, Math.min(MAX_SIDEBAR_WIDTH, viewportMax)));
  };

  const cleanupResizeListeners = () => {
    if (onResizeMoveRef.current) {
      window.removeEventListener('pointermove', onResizeMoveRef.current);
      onResizeMoveRef.current = null;
    }
    if (onResizeEndRef.current) {
      window.removeEventListener('pointerup', onResizeEndRef.current);
      window.removeEventListener('pointercancel', onResizeEndRef.current);
      onResizeEndRef.current = null;
    }
    document.body.style.cursor = '';
    document.body.style.userSelect = '';
  };

  useEffect(() => {
    return () => {
      cleanupResizeListeners();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleResizeStart = (e: React.PointerEvent<HTMLDivElement>) => {
    // Only allow resizing on desktop layouts.
    if (typeof window !== 'undefined' && window.innerWidth < 768) return;

    cleanupResizeListeners();
    isResizingRef.current = true;
    suppressSidebarToggleClickRef.current = false;
    resizeStartXRef.current = e.clientX;
    resizeStartWidthRef.current = sidebarWidth;

    document.body.style.cursor = 'col-resize';
    document.body.style.userSelect = 'none';

    const onMove = (ev: PointerEvent) => {
      if (!isResizingRef.current) return;
      const dx = ev.clientX - resizeStartXRef.current;
      if (Math.abs(dx) > 3) suppressSidebarToggleClickRef.current = true;
      setSidebarWidth(clampSidebarWidth(resizeStartWidthRef.current + dx));
      ev.preventDefault();
    };

    const onEnd = (ev: PointerEvent) => {
      if (!isResizingRef.current) return;
      isResizingRef.current = false;
      cleanupResizeListeners();
      ev.preventDefault();
    };

    onResizeMoveRef.current = onMove;
    onResizeEndRef.current = onEnd;
    window.addEventListener('pointermove', onMove, { passive: false });
    window.addEventListener('pointerup', onEnd, { passive: false });
    window.addEventListener('pointercancel', onEnd, { passive: false });

    // Avoid preventing default here so clicks still work when the user doesn't drag.
  };

  const handleDownload = () => {
    if (chartRef.current) {
      chartRef.current.exportImage();
    }
  };

  return (
    <div className="flex h-screen w-screen overflow-hidden relative" style={{ backgroundColor: 'var(--ui-bg)', color: 'var(--ui-text)' }}>
      
      {/* Mobile Sidebar Toggle - visible only on small screens or when closed */}
      <button 
        onClick={() => setIsSidebarOpen(!isSidebarOpen)}
        className="absolute top-4 left-4 z-30 p-2 rounded-lg shadow-md md:hidden"
        style={{ backgroundColor: 'var(--ui-overlay-bg)', border: '1px solid var(--ui-overlay-border)', color: 'var(--ui-text)' }}
      >
        {isSidebarOpen ? <X size={20} /> : <Menu size={20} />}
      </button>

      {/* Sidebar Container */}
      <div 
        className={`fixed md:relative inset-y-0 left-0 transform ${
          isSidebarOpen ? 'translate-x-0' : '-translate-x-full'
        } md:translate-x-0 transition-transform duration-300 ease-in-out z-20 h-full shadow-2xl md:shadow-none flex-shrink-0`}
        style={{ width: sidebarWidth }}
      >
        <InputPanel onDataUpdate={setData} currentData={data} />

        {/* Drag handle to resize sidebar (desktop) */}
        <div
          className="hidden md:block absolute inset-y-0 -right-2 w-4 cursor-col-resize touch-none z-40 pointer-events-auto hover:bg-indigo-100/40"
          onPointerDown={handleResizeStart}
          title="Drag to resize sidebar"
          aria-label="Resize sidebar"
          role="separator"
          aria-orientation="vertical"
        >
          <div className="absolute inset-y-0 right-1 w-px bg-slate-300/70" />
        </div>
        
        {/* Toggle Button for Desktop - Absolute on the edge of sidebar */}
        <button
           onPointerDown={(e) => handleResizeStart(e as unknown as React.PointerEvent<HTMLDivElement>)}
           onClick={() => {
             if (suppressSidebarToggleClickRef.current) {
               suppressSidebarToggleClickRef.current = false;
               return;
             }
             setIsSidebarOpen(false);
           }}
           className="hidden md:flex absolute top-1/2 -right-3 w-6 h-12 items-center justify-center rounded-r-lg shadow-md cursor-pointer z-50"
           style={{ backgroundColor: 'var(--ui-surface)', borderTop: '1px solid var(--ui-border)', borderRight: '1px solid var(--ui-border)', borderBottom: '1px solid var(--ui-border)', color: 'var(--ui-muted)' }}
           title="Collapse Sidebar"
        >
             <div className="w-1 h-4 bg-gray-300 rounded-full" />
        </button>
      </div>

      {/* Re-open button when sidebar is closed on desktop */}
      {!isSidebarOpen && (
         <button
         onClick={() => setIsSidebarOpen(true)}
        className="hidden md:flex absolute top-1/2 left-0 w-6 h-12 items-center justify-center rounded-r-lg shadow-md cursor-pointer z-50"
        style={{ backgroundColor: 'var(--ui-surface)', borderTop: '1px solid var(--ui-border)', borderRight: '1px solid var(--ui-border)', borderBottom: '1px solid var(--ui-border)', color: 'var(--ui-muted)' }}
         title="Expand Sidebar"
      >
           <div className="w-1 h-4 bg-gray-300 rounded-full" />
      </button>
      )}

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col h-full relative">
        {/* Toolbar */}
        <div className="absolute top-6 right-6 z-10 flex gap-4 items-start">

            {/* Site theme */}
            <div className="backdrop-blur rounded-lg shadow-sm px-3 py-2 flex items-center gap-2" style={{ backgroundColor: 'var(--ui-overlay-bg)', border: '1px solid var(--ui-overlay-border)', color: 'var(--ui-text)' }}>
              <label className="text-xs font-semibold" style={{ color: 'var(--ui-muted)' }} htmlFor="site-theme">
                Site theme
              </label>
              <select
                id="site-theme"
                value={siteThemeId}
                onChange={(e) => setSiteThemeId(e.target.value as SiteThemeId)}
                className="text-sm outline-none rounded-md px-2 py-1"
                style={{
                  color: 'var(--ui-text)',
                  backgroundColor: 'var(--ui-surface)',
                  border: '1px solid var(--ui-border)',
                }}
                title="Site theme"
              >
                {SITE_THEMES.map(t => (
                  <option key={t.id} value={t.id} style={{ backgroundColor: 'var(--ui-surface)', color: 'var(--ui-text)' }}>
                    {t.label}
                  </option>
                ))}
              </select>
            </div>

            {/* Chart theme */}
            <div className="backdrop-blur rounded-lg shadow-sm px-3 py-2 flex items-center gap-2" style={{ backgroundColor: 'var(--ui-overlay-bg)', border: '1px solid var(--ui-overlay-border)', color: 'var(--ui-text)' }}>
              <label className="text-xs font-semibold" style={{ color: 'var(--ui-muted)' }} htmlFor="chart-theme">
                Chart theme
              </label>
              <select
                id="chart-theme"
                value={chartThemeId}
                onChange={(e) => setChartThemeId(e.target.value as ChartThemeId)}
                className="text-sm outline-none rounded-md px-2 py-1"
                style={{
                  color: 'var(--ui-text)',
                  backgroundColor: 'var(--ui-surface)',
                  border: '1px solid var(--ui-border)',
                }}
                title="Chart theme"
              >
                {CHART_THEMES.map(t => (
                  <option key={t.id} value={t.id} style={{ backgroundColor: 'var(--ui-surface)', color: 'var(--ui-text)' }}>
                    {t.label}
                  </option>
                ))}
              </select>
            </div>
            
            {/* Aspect Ratio Control */}
            <div className="backdrop-blur rounded-lg shadow-sm p-2 flex flex-col gap-1 w-32" style={{ backgroundColor: 'var(--ui-overlay-bg)', border: '1px solid var(--ui-overlay-border)', color: 'var(--ui-text)' }}>
              <div className="flex items-center gap-2 text-xs font-semibold mb-1" style={{ color: 'var(--ui-muted)' }}>
                    <Ratio size={14} />
                    <span>Aspect Ratio</span>
                </div>
                <div className="flex items-center gap-2">
                    <input 
                        type="range" 
                        min="0.5" 
                        max="2" 
                        step="0.1" 
                        value={targetAspectRatio}
                        onChange={(e) => setTargetAspectRatio(parseFloat(e.target.value))}
                        className="w-full h-2 bg-indigo-100 rounded-lg appearance-none cursor-pointer accent-indigo-600"
                    />
                    <span className="text-xs w-6 text-right" style={{ color: 'var(--ui-muted)' }}>{targetAspectRatio}</span>
                </div>
            </div>

            {/* Download */}
            <button 
              onClick={handleDownload}
              className="backdrop-blur rounded-lg shadow-sm px-3 py-2 flex items-center gap-2 transition-all"
              style={{ backgroundColor: 'var(--ui-overlay-bg)', border: '1px solid var(--ui-overlay-border)', color: 'var(--ui-text)' }}
              title="Download image (PNG)"
            >
              <Download size={18} />
              <span className="text-sm font-medium">Download image</span>
            </button>
        </div>

        {/* Chart View */}
        <div className="flex-1 overflow-hidden" style={{ backgroundColor: 'var(--ui-bg)' }}>
          <OrgChart 
            ref={chartRef}
            data={data} 
            direction={LayoutDirection.TopDown} 
            targetAspectRatio={targetAspectRatio} 
            chartThemeId={chartThemeId}
          />
        </div>
      </div>
    </div>
  );
};

const App: React.FC = () => {
  return (
    <SiteThemeProvider>
      <ChartThemeProvider>
        <AppInner />
      </ChartThemeProvider>
    </SiteThemeProvider>
  );
};

export default App;

// src/app/app.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  NgZone,
  OnDestroy,
  OnInit,
  ViewChild,
  effect,
  inject,
  signal,
} from '@angular/core';
import { LucideAngularModule, Menu, X, Ratio, Download } from 'lucide-angular';
import { LayoutDirection, OrgChartNodeKeys, OrgNode } from './models/org.types';
import { ThemeService } from './core/theme.service';
import { INITIAL_DATA } from './constants/initial-data';
import { InputPanelComponent } from './components/input-panel/input-panel.component';
import { OrgChartComponent } from './components/org-chart/org-chart.component';

/**
 * App shell: sidebar (InputPanel) + main chart area (OrgChart), with toolbar
 * (theme selectors, aspect ratio, download) and a draggable
 * sidebar resize handle. State is held in signals; zoneless change detection.
 */
@Component({
  selector: 'app-root',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="shell" [class.shell--sidebar-open]="isSidebarOpen()">
      <!-- Mobile sidebar toggle -->
      <button
        type="button"
        class="mobile-toggle"
        (click)="isSidebarOpen.set(!isSidebarOpen())"
        title="Toggle sidebar"
      >
        @if (isSidebarOpen()) {
          <lucide-icon [img]="X" [size]="20" />
        } @else {
          <lucide-icon [img]="Menu" [size]="20" />
        }
      </button>

      <!-- Sidebar -->
      <div class="sidebar" [class.sidebar--open]="isSidebarOpen()">
        <app-input-panel
          [currentData]="data()"
          (dataChange)="data.set($event)"
        />
        <div
          class="resize-handle"
          (pointerdown)="onResizeStart($event)"
          title="Drag to resize sidebar"
          role="separator"
          [attr.aria-orientation]="'vertical'"
        ></div>
        <button
          type="button"
          class="sidebar-toggle sidebar-toggle--collapse"
          (click)="onToggleClick()"
          (pointerdown)="onTogglePointerDown($event)"
          title="Collapse Sidebar"
        >
          <span class="grip"></span>
        </button>
      </div>

      @if (!isSidebarOpen()) {
        <button
          type="button"
          class="sidebar-toggle sidebar-toggle--expand"
          (click)="isSidebarOpen.set(true)"
          title="Expand Sidebar"
        >
          <span class="grip"></span>
        </button>
      }

      <div class="main">
        <div class="toolbar">
          <div class="tool tool--select">
            <label for="site-theme">Site theme</label>
            <select
              id="site-theme"
              [value]="themeService.siteThemeId()"
              (change)="themeService.setSiteThemeId($any($event.target).value)"
            >
              @for (t of themeService.siteThemes; track t.id) {
                <option [value]="t.id">{{ t.label }}</option>
              }
            </select>
          </div>

          <div class="tool tool--select">
            <label for="chart-theme">Chart theme</label>
            <select
              id="chart-theme"
              [value]="themeService.chartThemeId()"
              (change)="themeService.setChartThemeId($any($event.target).value)"
            >
              @for (t of themeService.chartThemes; track t.id) {
                <option [value]="t.id">{{ t.label }}</option>
              }
            </select>
          </div>

          <div class="tool tool--ratio">
            <div class="ratio-header">
              <lucide-icon [img]="Ratio" [size]="14" />
              <span>Aspect Ratio</span>
            </div>
            <div class="ratio-row">
              <input
                type="range"
                min="0.25"
                max="4"
                step="0.05"
                [value]="targetAspectRatioUi()"
                (input)="onAspectRatioInput($event)"
                (pointerup)="commitAspectRatio()"
                (pointercancel)="commitAspectRatio()"
                (blur)="commitAspectRatio()"
              />
              <span class="ratio-value">{{ targetAspectRatioUi().toFixed(2) }}</span>
            </div>
          </div>

          <button
            type="button"
            class="tool tool--btn"
            (click)="handleDownload()"
            title="Download image (PNG)"
          >
            <lucide-icon [img]="Download" [size]="18" />
            <span>Download image</span>
          </button>

        </div>

        <div
          class="chart-view"
          [style.width.px]="isSidebarOpen() ? null : null"
        >
          <app-org-chart
            #chart
            [value]="data()"
            [collapsible]="true"
            [(collapsedKeys)]="collapsedKeys"
            [chartThemeId]="themeService.chartThemeId()"
            [direction]="LayoutDirection.TopDown"
            [targetAspectRatio]="targetAspectRatio()"
          />
        </div>
      </div>
    </div>
  `,
  imports: [LucideAngularModule, InputPanelComponent, OrgChartComponent],
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit, OnDestroy {
  readonly themeService = inject(ThemeService);
  private readonly zone = inject(NgZone);

  @ViewChild('chart', { static: false })
  chartRef?: OrgChartComponent;

  // Icon data exposed to the template for [img] bindings.
  readonly X = X;
  readonly Menu = Menu;
  readonly Ratio = Ratio;
  readonly Download = Download;

  readonly LayoutDirection = LayoutDirection;

  readonly data = signal<OrgNode>(INITIAL_DATA);
  readonly isSidebarOpen = signal(true);
  readonly collapsedKeys = signal<OrgChartNodeKeys>({});

  private readonly DEFAULT_SIDEBAR_WIDTH =
    typeof window !== 'undefined' && window.innerWidth >= 1024 ? 384 : 320;
  private readonly MIN_SIDEBAR_WIDTH = 280;
  private readonly MAX_SIDEBAR_WIDTH = 1200;
  private readonly MIN_CHART_WIDTH = 320;

  readonly sidebarWidth = signal<number>(this.DEFAULT_SIDEBAR_WIDTH);

  readonly targetAspectRatio = signal<number>(1);
  readonly targetAspectRatioUi = signal<number>(1);
  private ratioCommitTimeout: number | null = null;

  private resizing = false;
  private suppressToggleClick = false;
  private resizeStartX = 0;
  private resizeStartWidth = 0;
  private onResizeMove?: (e: PointerEvent) => void;
  private onResizeEnd?: (e: PointerEvent) => void;

  constructor() {
    effect(() => {
      this.themeService.siteThemeId();
      this.themeService.chartThemeId();
    });
  }

  ngOnInit(): void {
    this.themeService.init();
  }

  ngOnDestroy(): void {
    this.cleanupResizeListeners();
    if (this.ratioCommitTimeout !== null) {
      clearTimeout(this.ratioCommitTimeout);
    }
  }

  private clampSidebarWidth(width: number): number {
    const viewportMax =
      typeof window !== 'undefined'
        ? Math.max(this.MIN_SIDEBAR_WIDTH, window.innerWidth - this.MIN_CHART_WIDTH)
        : this.MAX_SIDEBAR_WIDTH;
    return Math.max(
      this.MIN_SIDEBAR_WIDTH,
      Math.min(width, Math.min(this.MAX_SIDEBAR_WIDTH, viewportMax)),
    );
  }

  onResizeStart(e: PointerEvent): void {
    if (typeof window !== 'undefined' && window.innerWidth < 768) return;
    this.cleanupResizeListeners();
    this.resizing = true;
    this.suppressToggleClick = false;
    this.resizeStartX = e.clientX;
    this.resizeStartWidth = this.sidebarWidth();
    document.body.style.cursor = 'col-resize';
    document.body.style.userSelect = 'none';

    const onMove = (ev: PointerEvent) => {
      if (!this.resizing) return;
      const dx = ev.clientX - this.resizeStartX;
      if (Math.abs(dx) > 3) this.suppressToggleClick = true;
      this.zone.run(() => {
        this.sidebarWidth.set(this.clampSidebarWidth(this.resizeStartWidth + dx));
      });
      ev.preventDefault();
    };
    const onEnd = (ev: PointerEvent) => {
      if (!this.resizing) return;
      this.resizing = false;
      this.cleanupResizeListeners();
      ev.preventDefault();
    };

    this.onResizeMove = onMove;
    this.onResizeEnd = onEnd;
    window.addEventListener('pointermove', onMove, { passive: false });
    window.addEventListener('pointerup', onEnd, { passive: false });
    window.addEventListener('pointercancel', onEnd, { passive: false });
  }

  onTogglePointerDown(e: PointerEvent): void {
    this.onResizeStart(e);
  }

  onToggleClick(): void {
    if (this.suppressToggleClick) {
      this.suppressToggleClick = false;
      return;
    }
    this.isSidebarOpen.set(false);
  }

  private cleanupResizeListeners(): void {
    if (this.onResizeMove) {
      window.removeEventListener('pointermove', this.onResizeMove);
      this.onResizeMove = undefined;
    }
    if (this.onResizeEnd) {
      window.removeEventListener('pointerup', this.onResizeEnd);
      window.removeEventListener('pointercancel', this.onResizeEnd);
      this.onResizeEnd = undefined;
    }
    document.body.style.cursor = '';
    document.body.style.userSelect = '';
  }

  onAspectRatioInput(e: Event): void {
    const next = parseFloat((e.target as HTMLInputElement).value);
    this.targetAspectRatioUi.set(next);
    this.scheduleAspectRatioCommit(next);
  }

  private scheduleAspectRatioCommit(value: number): void {
    if (this.ratioCommitTimeout !== null) {
      clearTimeout(this.ratioCommitTimeout);
    }
    this.ratioCommitTimeout = window.setTimeout(() => {
      this.ratioCommitTimeout = null;
      this.targetAspectRatio.set(value);
    }, 120);
  }

  commitAspectRatio(): void {
    if (this.ratioCommitTimeout !== null) {
      clearTimeout(this.ratioCommitTimeout);
      this.ratioCommitTimeout = null;
    }
    this.targetAspectRatio.set(this.targetAspectRatioUi());
  }

  handleDownload(): void {
    this.chartRef?.exportImage();
  }
}
